### ISSUE TITLE
Error in prepare_submission.py

### ISSUE THREAD

**Issue by yuzhenmao** [tau-nlp/zero_scrolls#1]
Hi,

Thank you for the amazing work! I got an error when I run prepare_submission.py. 

(my cmd: python prepare_submission.py --quality_file generations/google_flan_t5_small/quality/preds.jsonl  --xxxxxxx)

<img width="697" alt="Screenshot 2023-08-27 at 3 14 01 PM" src="https://github.com/tau-nlp/zero_scrolls/assets/57878927/21ee155f-a7ac-4c9d-b208-2806aa9ba8f3">

Could you help me to take a look at it? Thanks!

**Comment by yuzhenmao** [comment]
One additional information is that the output file I generated is .jsonl (not .json). And it looks like this:
<img width="580" alt="Screenshot 2023-08-28 at 5 26 04 PM" src="https://github.com/tau-nlp/zero_scrolls/assets/57878927/17df0a8b-bfe2-4203-82b4-5c7b5568cfa2">


It is weird, since I used the original code to genereate the output.

**Comment by yuzhenmao** [comment]
@UriSha I think there is something wrong with the json writing part in the original code (hf/run_hf_model.py). Thanks!

**Comment by UriSha** [comment]
Hi @yuzhenmao, 
Thanks!
You are absolutely right, sorry and I will push a fix to the writing end soon :)

For now you can rewrite your predictions files with something like:

```
import json

input_file_path = 'your/path/gov_report/predictions.jsonl'
output_file_path =  'your/path/gov_report/predictions.json'

preds = {}

with open(input_file_path, 'r') as input_file:
    for line in input_file:
        json_data = json.loads(line)
        preds[json_data['id']] = json_data['prediction']

with open(output_file_path, 'w') as output_file:
    json.dump(preds, output_file)
```

**Comment by yuzhenmao** [comment]
Thanks, @UriSha !

**Comment by UriSha** [comment]
Sure, thank you!
Just pushed the fix.
